import { DIRECTIONS, DIFFICULTIES } from '@/lib/config';
import type { Coordinate, DifficultyId } from '@/lib/types';

/**
 * Generate GPX XML string from route data.
 */
export function generateGPX(
  routedCoords: Coordinate[] | null,
  guideWaypoints: Coordinate[] | null,
  distance: number,
  heading: number,
  difficulty: DifficultyId,
  routedDistanceKm: number | null,
): string {
  const coords =
    routedCoords ||
    (guideWaypoints
      ? [...guideWaypoints, guideWaypoints[0]]
      : []);
  const dir = DIRECTIONS.find((d) => d.angle === heading)?.short || '';
  const diff = DIFFICULTIES[difficulty];
  const now = new Date().toISOString();
  const distLabel = routedDistanceKm
    ? `${routedDistanceKm}km`
    : `${distance}km`;

  let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="RatataLabs Offroad Loop Planner"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>Offroad Loop - ${distLabel} ${dir} ${diff.label}</name>
    <desc>Generated by RatataLabs Offroad Loop Planner. Difficulty: ${diff.label} (${diff.desc})</desc>
    <time>${now}</time>
  </metadata>
  <trk>
    <name>Offroad Loop ${distLabel} ${dir} ${diff.label}</name>
    <type>Offroad</type>
    <trkseg>
`;

  coords.forEach((c) => {
    gpx += `      <trkpt lat="${c[0].toFixed(6)}" lon="${c[1].toFixed(6)}"></trkpt>\n`;
  });

  gpx += `    </trkseg>
  </trk>
`;

  if (guideWaypoints) {
    guideWaypoints.forEach((wp, i) => {
      const name = i === 0 ? 'Start' : `WP${i}`;
      gpx += `  <wpt lat="${wp[0].toFixed(6)}" lon="${wp[1].toFixed(6)}">
    <name>${name}</name>
    <sym>${i === 0 ? 'Flag, Green' : 'Waypoint'}</sym>
  </wpt>\n`;
    });
  }

  gpx += `</gpx>`;
  return gpx;
}

/**
 * Build a filename for the GPX download.
 */
export function getFilename(
  heading: number,
  difficulty: DifficultyId,
  routedDistanceKm: number | null,
  distance: number,
): string {
  const dir =
    DIRECTIONS.find((d) => d.angle === heading)?.short.toLowerCase() || 'loop';
  const dist = routedDistanceKm || distance;
  return `offroad-${dist}km-${dir}-${difficulty}.gpx`;
}

/**
 * Trigger a GPX file download in the browser.
 */
export function downloadGPX(
  routedCoords: Coordinate[] | null,
  guideWaypoints: Coordinate[] | null,
  distance: number,
  heading: number,
  difficulty: DifficultyId,
  routedDistanceKm: number | null,
): void {
  const gpx = generateGPX(
    routedCoords,
    guideWaypoints,
    distance,
    heading,
    difficulty,
    routedDistanceKm,
  );
  const blob = new Blob([gpx], { type: 'application/gpx+xml' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = getFilename(heading, difficulty, routedDistanceKm, distance);
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
